name: example
description:
  Example showing how to use error_templates.

homepage: https://github.com/simphotonics/error_templates

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  error_template:
    path: ../
